repository:
  # Either `true` to enable issues for this repository, `false` to disable them.
  has_issues: false
  
  topics: martijn, test

labels:
  - name: feature
    description: New functionality
